services:
  quizapp:
    image: goosebooze/quizapp:1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/quizapp
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  frontend:
    image: goosebooze/quizapp-frontend:1.0.0
    ports:
      - "8080:80"

volumes:
  mongo-data: {}